//    ___    ____    _____   ____       ____    ___    ____    _____ 
//   / _ \  |  _ \  | ____| / ___|     / ___|  / _ \  |  _ \  | ____|
//  | | | | | |_) | |  _|   \___ \    | |     | | | | | |_) | |  _|  
//  | |_| | |  _ <  | |___   ___) |   | |___  | |_| | |  _ <  | |___ 
//   \___/  |_| \_\ |_____| |____/     \____|  \___/  |_| \_\ |_____|
//
// [ ORES CORE ] - Common Module
//
// Description: Static database containing all material definitions.
//
// Author: __mathieu
// Version: 26.1.001
//
// License: CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike)
// This code is free to be copied, shared, and adapted under the terms 
// of the Creative Commons NC-SA license. 
// Commercial use is strictly prohibited.
//

package ores.mathieu.material;

import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.material.PushReaction;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;
import java.util.HashMap;
import java.util.Map;

public class MaterialsDatabase {
    public static final Map<String, Material> MATERIALS = new HashMap<>();
    static {
        MATERIALS.put("iron", new Material()
            .setName("iron")
            .setNameEN("Iron").setNameFR("Fer").setNameES("Hierro").setNameIT("Ferro").setNameDE("Eisen")
            .setNamePT("Ferro").setNameRU("Железо").setNameZH("铁").setNameJP("鉄")
            .setBaseColorHigh(14211288).setRawColorHigh(0xD8D8D8).setRawColorLow(0x9E836A)
            .setBaseType("ingot")
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(3.33f)
            .setBlockResistanceFactor(1.00f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f)
            .setOreResistanceFactor(1.00f)
            .setMiningLevel(1)
            .setOreDropItem("raw_iron")
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("gold", new Material()
            .setName("gold")
            .setNameEN("Gold").setNameFR("Or").setNameES("Oro").setNameIT("Oro").setNameDE("Gold")
            .setNamePT("Ouro").setNameRU("Золото").setNameZH("金").setNameJP("金")
            .setBaseColorHigh(16641624).setRawColorHigh(0xFDE060).setRawColorLow(0x9E9783)
            .setBaseType("ingot")
            .setBeacon(true)
            .setPiglinLoved(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(1.00f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(1.00f)
            .setMiningLevel(2)
            .setOreDropItem("raw_gold")
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("copper", new Material()
            .setName("copper")
            .setNameEN("Copper").setNameFR("Cuivre").setNameES("Cobre").setNameIT("Rame").setNameDE("Kupfer")
            .setNamePT("Cobre").setNameRU("Медь").setNameZH("铜").setNameJP("銅")
            .setBaseColorHigh(15170646).setRawColorHigh(0xE77C56).setRawColorLow(0x3B9C7A)
            .setBaseType("ingot")
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(1.00f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(1.00f)
            .setMiningLevel(1)
            .setOreDropItem("raw_copper")
            .setOreSmeltingXP(0.7f)
            .setOreDropMin(1)
            .setOreDropMax(5)
            );
        MATERIALS.put("coal", new Material()
            .setName("coal")
            .setNameEN("Coal").setNameFR("Charbon").setNameES("Carbón").setNameIT("Carbone").setNameDE("Kohle")
            .setNamePT("Carvão").setNameRU("Уголь").setNameZH("煤").setNameJP("石炭")
            .setBaseColorHigh(3158064).setRawColorHigh(0x303030).setRawColorLow(0x181818)
            .setBaseType("self")
            .setBeacon(true)
            .setFuelTime(1600)
            .setTrimmable(false)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(0.50f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(0.50f)
            .setMiningLevel(0)
            .setOreDropItem("minecraft:coal")
            .setOreDropXPMax(2)
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("diamond", new Material()
            .setName("diamond")
            .setNameEN("Diamond").setNameFR("Diamant").setNameES("Diamante").setNameIT("Diamante").setNameDE("Diamant")
            .setNamePT("Diamante").setNameRU("Алмаз").setNameZH("钻石").setNameJP("ダイヤモンド")
            .setBaseColorHigh(6158051)
            .setBaseType("self")
            .setRarity(Rarity.UNCOMMON)
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(3.33f)
            .setBlockResistanceFactor(1.00f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f)
            .setOreResistanceFactor(1.00f)
            .setMiningLevel(2)
            .setOreDropItem("minecraft:diamond")
            .setOreDropXPMin(3)
            .setOreDropXPMax(7)
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("emerald", new Material()
            .setName("emerald")
            .setNameEN("Emerald").setNameFR("Émeraude").setNameES("Esmeralda").setNameIT("Smeraldo").setNameDE("Smaragd")
            .setNamePT("Esmeralda").setNameRU("Изумруд").setNameZH("绿宝石").setNameJP("エメラルド")
            .setBaseColorHigh(1564002).setRawColorHigh(0x17DD62).setRawColorLow(0x0E823A)
            .setBaseType("self")
            .setRarity(Rarity.UNCOMMON)
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(3.33f)
            .setBlockResistanceFactor(1.00f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f)
            .setOreResistanceFactor(1.00f)
            .setMiningLevel(2)
            .setOreDropItem("minecraft:emerald")
            .setOreDropXPMin(3)
            .setOreDropXPMax(7)
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("lapis", new Material()
            .setName("lapis")
            .setNameEN("Lapis").setNameFR("Lapis").setNameES("Lapis").setNameIT("Lapis").setNameDE("Lapis")
            .setNamePT("Lápis").setNameRU("Лазурит").setNameZH("青金石").setNameJP("ラピスラズリ")
            .setBaseItemName("lapis_lazuli")
            .setBaseColorHigh(2247599).setRawColorHigh(0x224Baf).setRawColorLow(0x122B69)
            .setBaseType("self")
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(0.50f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(0.50f)
            .setMiningLevel(1)
            .setOreDropItem("minecraft:lapis_lazuli")
            .setOreDropMax(8)
            .setOreDropXPMin(2)
            .setOreDropXPMax(5)
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("redstone", new Material()
            .setName("redstone")
            .setNameEN("Redstone").setNameFR("Redstone").setNameES("Redstone").setNameIT("Redstone").setNameDE("Redstone")
            .setNamePT("Redstone").setNameRU("Редстоун").setNameZH("红石").setNameJP("レッドストーン")
            .setBaseColorHigh(16711680).setRawColorHigh(0xFF0000).setRawColorLow(0x8A0000)
            .setBaseType("self")

            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(0.50f)
            .setBlockRedstonePower(15)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(0.50f)
            .setMiningLevel(2)
            .setOreDropItem("minecraft:redstone")
            .setOreDropMax(5)
            .setOreDropXPMin(1)
            .setOreDropXPMax(5)
            .setOreLightLevel(9)
            .setOreLightMode("DYNAMIC")
            .setOreParticleMode("DYNAMIC")
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("quartz", new Material()

            .setName("quartz")
            .setNameEN("Quartz").setNameFR("Quartz").setNameES("Cuarzo").setNameIT("Quarzo").setNameDE("Quarz")
            .setNamePT("Quartzo").setNameRU("Кварц").setNameZH("石英").setNameJP("クォーツ")
            .setBaseColorHigh(15395562).setRawColorHigh(0xEAEAEA).setRawColorLow(0x9E9E9E)
            .setBaseType("self")
            .setBeacon(true)
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f)
            .setBlockResistanceFactor(0.50f)
            .setSound(SoundType.METAL)
            .setInstrument(NoteBlockInstrument.IRON_XYLOPHONE)
            .setMapColor(MapColor.METAL)
            .setCompressionRatio(4)
            .setOreHardnessFactor(2.00f)
            .setOreResistanceFactor(0.50f)
            .setMiningLevel(0)
            .setOreDropItem("minecraft:quartz")
            .setOreDropXPMin(2)
            .setOreDropXPMax(5)
            .setOreSmeltingXP(0.7f)
            );
        MATERIALS.put("aluminum", new Material()
            .setName("aluminum").setNameEN("Aluminum").setNameFR("Aluminium").setNameES("Aluminio").setNameIT("Alluminio").setNameDE("Aluminium")
            .setNamePT("Alumínio").setNameRU("Алюминий").setNameZH("铝").setNameJP("アルミニウム").setBaseColorHigh(0xD6DCE6).setRawColorHigh(0xD6DCE6).setRawColorLow(0x8E959E).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.50f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("raw_aluminum").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("lead", new Material()
            .setName("lead").setNameEN("Lead").setNameFR("Plomb").setNameES("Plomo").setNameIT("Piombo").setNameDE("Blei")
            .setNamePT("Chumbo").setNameRU("Свинец").setNameZH("铅").setNameJP("铅").setBaseColorHigh(0x4D4D66).setRawColorHigh(0x4D4D66).setRawColorLow(0x272733).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.67f).setMiningLevel(1).setOreDropItem("raw_lead").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("nickel", new Material()
            .setName("nickel").setNameEN("Nickel").setNameFR("Nickel").setNameES("Níquel").setNameIT("Nichel").setNameDE("Nickel")
            .setNamePT("Níquel").setNameRU("Никель").setNameZH("镍").setNameJP("ニッケル").setBaseColorHigh(0x909060).setRawColorHigh(0x909060).setRawColorLow(0x505030).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_nickel").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("osmium", new Material().setFuelTime(1600)
            .setName("osmium").setNameEN("Osmium").setNameFR("Osmium").setNameES("Osmio").setNameIT("Osmio").setNameDE("Osmium")
            .setNamePT("Ósmio").setNameRU("Осмий").setNameZH("锇").setNameJP("オスミウム").setBaseColorHigh(0xBED6E0).setRawColorHigh(0xBED6E0).setRawColorLow(0x617680).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.33f).setMiningLevel(2).setOreDropItem("raw_osmium").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("platinum", new Material()
            .setName("platinum").setNameEN("Platinum").setNameFR("Platine").setNameES("Platino").setNameIT("Platino").setNameDE("Platin")
            .setNamePT("Platina").setNameRU("Платина").setNameZH("铂").setNameJP("白金").setBaseColorHigh(0x5601FF).setRawColorHigh(0x5601FF).setRawColorLow(0x2A0080).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_platinum").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("silver", new Material()
            .setName("silver").setNameEN("Silver").setNameFR("Argent").setNameES("Plata").setNameIT("Argento").setNameDE("Silber")
            .setNamePT("Prata").setNameRU("Серебро").setNameZH("银").setNameJP("銀").setBaseColorHigh(0xC0C0D0).setRawColorHigh(0xC0C0D0).setRawColorLow(0x6A6A7A).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.83f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.83f).setMiningLevel(2).setOreDropItem("raw_silver").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("tin", new Material()
            .setName("tin").setNameEN("Tin").setNameFR("Étain").setNameES("Estaño").setNameIT("Stagno").setNameDE("Zinn")
            .setNamePT("Estanho").setNameRU("Олово").setNameZH("锡").setNameJP("スズ").setBaseColorHigh(0x98A1A5).setRawColorHigh(0x98A1A5).setRawColorLow(0x515659).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.50f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("raw_tin").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("uranium", new Material()
            .setName("uranium").setNameEN("Uranium").setNameFR("Uranium").setNameES("Uranio").setNameIT("Uranio").setNameDE("Uran")
            .setNamePT("Urânio").setNameRU("Уран").setNameZH("铀").setNameJP("ウラン").setBaseColorHigh(0x449B21).setRawColorHigh(0x449B21).setRawColorLow(0x1B400C).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.33f).setMiningLevel(2).setOreDropItem("raw_uranium").setOreSmeltingXP(1.0f).setOreParticleMode("ALWAYS").setOreParticleIntensity(10.0f)
        );
        MATERIALS.put("zinc", new Material()
            .setName("zinc").setNameEN("Zinc").setNameFR("Zinc").setNameES("Zinc").setNameIT("Zinco").setNameDE("Zink")
            .setNamePT("Zinco").setNameRU("Цинк").setNameZH("锌").setNameJP("亜鉛").setBaseColorHigh(0xDBE4BB).setRawColorHigh(0xDBE4BB).setRawColorLow(0x71785B).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.50f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("raw_zinc").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("iridium", new Material()
            .setName("iridium").setNameEN("Iridium").setNameFR("Iridium").setNameES("Iridio").setNameIT("Iridio").setNameDE("Iridium")
            .setNamePT("Irídio").setNameRU("Иридий").setNameZH("铱").setNameJP("イリジウム").setBaseColorHigh(0xE2D5E6).setRawColorHigh(0xE2D5E6).setRawColorLow(0x7B6C80).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(3.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(3.33f).setMiningLevel(4).setOreDropItem("raw_iridium").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("netherite", new Material()
            .setName("netherite").setNameEN("Netherite").setNameFR("Netherite").setNameES("Netherita").setNameIT("Netherite").setNameDE("Netherit")
            .setNamePT("Netherita").setNameRU("Нетерит").setNameZH("下界合金").setNameJP("ネザライト").setBaseColorHigh(0x443F41).setRawColorHigh(0x443F41).setRawColorLow(0x221F20).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(33.33f).setBlockResistanceFactor(200.00f).setSound(SoundType.NETHERITE_BLOCK).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(20.00f).setOreResistanceFactor(200.00f).setMiningLevel(3).setOreDropItem("netherite_scrap").setOreSmeltingXP(2.0f).setDebrisName("ancient_debris").setOrePushReaction(PushReaction.BLOCK)
        );
        MATERIALS.put("steel", new Material()
            .setName("steel").setNameEN("Steel").setNameFR("Acier").setNameES("Acero").setNameIT("Acciaio").setNameDE("Stahl")
            .setNamePT("Aço").setNameRU("Сталь").setNameZH("钢").setNameJP("特鋼").setBaseColorHigh(0x666666).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(2.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(4.00f).setOreResistanceFactor(2.00f).setMiningLevel(2).setOreDropItem("raw_steel").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("invar", new Material()
            .setName("invar").setNameEN("Invar").setNameFR("Invar").setNameES("Invar").setNameIT("Invar").setNameDE("Invar")
            .setNamePT("Invar").setNameRU("Инвар").setNameZH("因瓦合金").setNameJP("インバー").setBaseColorHigh(0xA5A591).setRawColorHigh(0xA5A591).setRawColorLow(0x525248).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.67f).setMiningLevel(2).setOreDropItem("raw_invar").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("electrum", new Material()
            .setName("electrum").setNameEN("Electrum").setNameFR("Électrum").setNameES("Electro").setNameIT("Elettro").setNameDE("Elektrum")
            .setNamePT("Eletro").setNameRU("Электрум").setNameZH("琥珀金").setNameJP("エレクトラム").setBaseColorHigh(0xE6E673).setRawColorHigh(0xE6E673).setRawColorLow(0x737339).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true).setPiglinLoved(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.83f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.GOLD)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.83f).setMiningLevel(2).setOreDropItem("raw_electrum").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("bronze", new Material()
            .setName("bronze").setNameEN("Bronze").setNameFR("Bronze").setNameES("Bronce").setNameIT("Bronzo").setNameDE("Bronze")
            .setNamePT("Bronze").setNameRU("Бронза").setNameZH("青铜").setNameJP("青銅").setBaseColorHigh(0xCD7F32).setRawColorHigh(0xCD7F32).setRawColorLow(0x663F19).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_ORANGE)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_bronze").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("brass", new Material()
            .setName("brass").setNameEN("Brass").setNameFR("Laiton").setNameES("Latón").setNameIT("Ottone").setNameDE("Messing")
            .setNamePT("Latão").setNameRU("Латунь").setNameZH("黄铜").setNameJP("真鍮").setBaseColorHigh(0xE1C16E).setRawColorHigh(0xE1C16E).setRawColorLow(0x706037).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.GOLD)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_brass").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("enderium", new Material()
            .setName("enderium").setNameEN("Enderium").setNameFR("Enderium").setNameES("Enderio").setNameIT("Enderio").setNameDE("Enderium")
            .setNamePT("Endério").setNameRU("Эндериум").setNameZH("末影合金").setNameJP("エンデリウム").setBaseColorHigh(0x006666).setRawColorHigh(0x00A3A3).setRawColorLow(0x003333).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(13.33f).setBlockResistanceFactor(200.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_CYAN).setBlockLightLevel(7)
            .setOreHardnessFactor(13.33f).setOreResistanceFactor(200.00f).setMiningLevel(4).setOreDropItem("raw_enderium").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("lumium", new Material()
            .setName("lumium").setNameEN("Lumium").setNameFR("Lumium").setNameES("Lumio").setNameIT("Lumio").setNameDE("Lumium")
            .setNamePT("Lúmio").setNameRU("Люмиум").setNameZH("流明合金").setNameJP("ルミウム").setBaseColorHigh(0xFFFFCC).setRawColorHigh(0xFFFFCC).setRawColorLow(0x7F7F66).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_YELLOW).setBlockLightLevel(15).setBlockLightMode("ALWAYS")
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_lumium").setOreSmeltingXP(1.0f).setOreLightLevel(10).setOreLightMode("ALWAYS")
        );
        MATERIALS.put("signalum", new Material()
            .setName("signalum").setNameEN("Signalum").setNameFR("Signalum").setNameES("Signalio").setNameIT("Segnalio").setNameDE("Signalum")
            .setNamePT("Sinalium").setNameRU("Сигналум").setNameZH("信号合金").setNameJP("シグナラム").setBaseColorHigh(0xFF6600).setRawColorHigh(0xFF6600).setRawColorLow(0x7F3300).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_RED).setBlockRedstonePower(30)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_signalum").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("constantan", new Material()
            .setName("constantan").setNameEN("Constantan").setNameFR("Constantan").setNameES("Constantán").setNameIT("Costantana").setNameDE("Konstantan")
            .setNamePT("Constantan").setNameRU("Константан").setNameZH("康铜合金").setNameJP("コンスタンタン").setBaseColorHigh(0xCC9966).setRawColorHigh(0xCC9966).setRawColorLow(0x664C33).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_ORANGE)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_constantan").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("neptunium", new Material()
            .setName("neptunium").setNameEN("Neptunium").setNameFR("Neptunium").setNameES("Neptunio").setNameIT("Nettunio").setNameDE("Neptunium")
            .setNamePT("Neptúnio").setNameRU("Нептуний").setNameZH("镎").setNameJP("ネプツニウム").setBaseColorHigh(0x00CCFF).setRawColorHigh(0x00CCFF).setRawColorLow(0x00667F).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(4.00f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_neptunium").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("blutonium", new Material()
            .setName("blutonium").setNameEN("Blutonium").setNameFR("Blutonium").setNameES("Blutonio").setNameIT("Blutonio").setNameDE("Blutonium")
            .setNamePT("Blutónio").setNameRU("Блутоний").setNameZH("蓝金").setNameJP("ブルトニウム").setBaseColorHigh(0x0000FF).setRawColorHigh(0x0000FF).setRawColorLow(0x00007F).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(5.33f).setBlockResistanceFactor(6.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLUE)
            .setOreHardnessFactor(5.33f).setOreResistanceFactor(6.67f).setMiningLevel(4).setOreDropItem("blutonium").setOreSmeltingXP(2.0f).setOreLightLevel(5).setOreLightMode("ALWAYS")
        );
        MATERIALS.put("cyanite", new Material()
            .setName("cyanite").setNameEN("Cyanite").setNameFR("Cyanite").setNameES("Cianita").setNameIT("Cianite").setNameDE("Cyanit")
            .setNamePT("Cianita").setNameRU("Кианит").setNameZH("蓝晶石").setNameJP("カヤナイト").setBaseColorHigh(0x00FFFF).setRawColorHigh(0x00FFFF).setRawColorLow(0x007F7F).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_CYAN)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_cyanite").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("magentite", new Material()
            .setName("magentite").setNameEN("Magentite").setNameFR("Magentite").setNameES("Magentita").setNameIT("Magentite").setNameDE("Magentit")
            .setNamePT("Magentita").setNameRU("Магентит").setNameZH("玛琴合金").setNameJP("マゲンタイト").setBaseColorHigh(0xFF00FF).setRawColorHigh(0xFF00FF).setRawColorLow(0x7F007F).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_MAGENTA)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_magentite").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("ludicrite", new Material()
            .setName("ludicrite").setNameEN("Ludicrite").setNameFR("Ludicrite").setNameES("Ludicrita").setNameIT("Ludicrite").setNameDE("Ludicrit")
            .setNamePT("Ludicrita").setNameRU("Лудикрит").setNameZH("路迪合金").setNameJP("ルディクライト").setBaseColorHigh(0xFF00CC).setRawColorHigh(0xFF00CC).setRawColorLow(0x7F0066).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(13.33f).setBlockResistanceFactor(33.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_PINK)
            .setOreHardnessFactor(13.33f).setOreResistanceFactor(33.33f).setMiningLevel(4).setOreDropItem("raw_ludicrite").setOreSmeltingXP(5.0f).setOreLightLevel(10).setOreLightMode("DYNAMIC")
        );
        MATERIALS.put("ridiculite", new Material()
            .setName("ridiculite").setNameEN("Ridiculite").setNameFR("Ridiculite").setNameES("Ridiculita").setNameIT("Ridiculite").setNameDE("Ridiculit")
            .setNamePT("Ridiculita").setNameRU("Ридикулит").setNameZH("里迪合金").setNameJP("リディクライト").setBaseColorHigh(0xCCFF00).setRawColorHigh(0xCCFF00).setRawColorLow(0x667F00).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(12.00f).setBlockResistanceFactor(30.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_GREEN)
            .setOreHardnessFactor(12.00f).setOreResistanceFactor(30.00f).setMiningLevel(4).setOreDropItem("raw_ridiculite").setOreSmeltingXP(4.0f).setOreLightLevel(8).setOreLightMode("DYNAMIC")
        );
        MATERIALS.put("inanite", new Material()
            .setName("inanite").setNameEN("Inanite").setNameFR("Inanite").setNameES("Inanita").setNameIT("Inanite").setNameDE("Inanit")
            .setNamePT("Inanita").setNameRU("Инанит").setNameZH("因南合金").setNameJP("イナナイト").setBaseColorHigh(0x333333).setRawColorHigh(0x333333).setRawColorLow(0x191919).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(20.00f).setBlockResistanceFactor(83.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(20.00f).setOreResistanceFactor(83.33f).setMiningLevel(4).setOreDropItem("raw_inanite").setOreSmeltingXP(10.0f)
        );
        MATERIALS.put("insanite", new Material()
            .setName("insanite").setNameEN("Insanite").setNameFR("Insanite").setNameES("Insanita").setNameIT("Insanite").setNameDE("Insanit")
            .setNamePT("Insanita").setNameRU("Инсанит").setNameZH("英三合金").setNameJP("インサナイト").setBaseColorHigh(0x111111).setRawColorHigh(0x111111).setRawColorLow(0x080808).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(26.67f).setBlockResistanceFactor(166.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(26.67f).setOreResistanceFactor(166.67f).setMiningLevel(5).setOreDropItem("raw_insanite").setOreSmeltingXP(20.0f)
        );
        MATERIALS.put("deorum", new Material()
            .setName("deorum").setNameEN("Deorum").setNameFR("Deorum").setNameES("Deorum").setNameIT("Deorum").setNameDE("Deorum")
            .setNamePT("Deorum").setNameRU("Деорум").setNameZH("迪欧姆").setNameJP("デオラム").setBaseColorHigh(0xFFD700).setRawColorHigh(0xFFD700).setRawColorLow(0x7F6B00).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true).setPiglinLoved(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(8.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.GOLD)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(8.33f).setMiningLevel(4).setOreDropItem("raw_deorum").setOreSmeltingXP(5.0f)
        );
        MATERIALS.put("mithril", new Material()
            .setName("mithril").setNameEN("Mithril").setNameFR("Mithril").setNameES("Mitril").setNameIT("Mitril").setNameDE("Mithril")
            .setNamePT("Mitril").setNameRU("Мифрил").setNameZH("秘银").setNameJP("ミスリル").setBaseColorHigh(0x80D0FF).setRawColorHigh(0x80D0FF).setRawColorLow(0x40687F).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(8.00f).setBlockResistanceFactor(13.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(8.00f).setOreResistanceFactor(13.33f).setMiningLevel(4).setOreDropItem("raw_mithril").setOreSmeltingXP(3.0f)
        );
        MATERIALS.put("pyrium", new Material()
            .setName("pyrium").setNameEN("Pyrium").setNameFR("Pyrium").setNameES("Pirio").setNameIT("Pirio").setNameDE("Pyrium")
            .setNamePT("Pírio").setNameRU("Пириум").setNameZH("火合金").setNameJP("パイリウム").setBaseColorHigh(0xFF4500).setRawColorHigh(0xFF4500).setRawColorLow(0x7F2200).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(5.33f).setBlockResistanceFactor(6.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_ORANGE).setIgnitedByLava(true)
            .setOreHardnessFactor(5.33f).setOreResistanceFactor(6.67f).setMiningLevel(4).setOreDropItem("raw_pyrium").setOreSmeltingXP(2.0f).setOreLightLevel(5).setOreLightMode("DYNAMIC")
        );
        MATERIALS.put("arcane", new Material()
            .setName("arcane").setNameEN("Arcane").setNameFR("Arcane").setNameES("Arcano").setNameIT("Arcano").setNameDE("Arkan")
            .setNamePT("Arcano").setNameRU("Аркан").setNameZH("奥术").setNameJP("アルケイン").setBaseColorHigh(0x6633FF).setRawColorHigh(0x6633FF).setRawColorLow(0x33197F).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_arcane").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("ferricore", new Material()
            .setName("ferricore").setNameEN("Ferricore").setNameFR("Ferricore").setNameES("Ferricore").setNameIT("Ferricore").setNameDE("Ferricore")
            .setNamePT("Ferricore").setNameRU("Феррикор").setNameZH("铁芯合金").setNameJP("フェリコア").setBaseColorHigh(0x7A7A7A).setRawColorHigh(0x7A7A7A).setRawColorLow(0x3D3D3D).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_ferricore").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("blazegold", new Material()
            .setName("blazegold").setNameEN("Blaze Gold").setNameFR("Or de Blaze").setNameES("Oro de Blaze").setNameIT("Oro di Blaze").setNameDE("Blaze-Gold")
            .setNamePT("Ouro de Blaze").setNameRU("Блейз-голд").setNameZH("烈焰金").setNameJP("ブレイズゴールド").setBaseColorHigh(0xFFCC00).setRawColorHigh(0xFFCC00).setRawColorLow(0x7F6600).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true).setPiglinLoved(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.GOLD).setIgnitedByLava(true)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_blazegold").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("eclipse_alloy", new Material()
            .setName("eclipse_alloy").setNameEN("Eclipse Alloy").setNameFR("Alliage d'Éclipse").setNameES("Aleación de Eclipse").setNameIT("Lega di Eclissi").setNameDE("Finsternis-Legierung")
            .setNamePT("Liga de Eclipse").setNameRU("Сплав затмения").setNameZH("日蚀合金").setNameJP("エクリプス合金").setBaseColorHigh(0x330033).setRawColorHigh(0x330033).setRawColorLow(0x190019).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(8.00f).setBlockResistanceFactor(13.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(8.00f).setOreResistanceFactor(13.33f).setMiningLevel(4).setOreDropItem("raw_eclipse_alloy").setOreSmeltingXP(3.0f)
        );
        MATERIALS.put("witherite", new Material()
            .setName("witherite").setNameEN("Witherite").setNameFR("Withérite").setNameES("Witherita").setNameIT("Witherite").setNameDE("Witherit")
            .setNamePT("Witherita").setNameRU("Витерит").setNameZH("凋灵合金").setNameJP("ウィザライト").setBaseColorHigh(0x1F1F1F).setRawColorHigh(0x1F1F1F).setRawColorLow(0x0F0F0F).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(10.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(10.00f).setMiningLevel(4).setOreDropItem("raw_witherite").setOreSmeltingXP(2.5f)
        );
        MATERIALS.put("ancient_metal", new Material()
            .setName("ancient_metal").setNameEN("Ancient Metal").setNameFR("Métal Ancien").setNameES("Metal Antiguo").setNameIT("Metallo Antico").setNameDE("Antikes Metall")
            .setNamePT("Metal Antigo").setNameRU("Древний металл").setNameZH("古代金属").setNameJP("古代の金属").setBaseColorHigh(0x70665A).setRawColorHigh(0x70665A).setRawColorLow(0x38332D).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(5.33f).setBlockResistanceFactor(6.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BROWN)
            .setOreHardnessFactor(5.33f).setOreResistanceFactor(6.67f).setMiningLevel(3).setOreDropItem("raw_ancient_metal").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("black_steel", new Material()
            .setName("black_steel").setNameEN("Black Steel").setNameFR("Acier Noir").setNameES("Acero Negro").setNameIT("Acciaio Nero").setNameDE("Schwarzstahl")
            .setNamePT("Aço Negro").setNameRU("Черная сталь").setNameZH("黑钢").setNameJP("黒鋼").setBaseColorHigh(0x222222).setRawColorHigh(0x222222).setRawColorLow(0x111111).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(8.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(8.33f).setMiningLevel(4).setOreDropItem("raw_black_steel").setOreSmeltingXP(2.5f)
        );
        MATERIALS.put("ignitium", new Material()
            .setName("ignitium").setNameEN("Ignitium").setNameFR("Ignitium").setNameES("Ignitio").setNameIT("Ignitio").setNameDE("Ignitium")
            .setNamePT("Ignítio").setNameRU("Игнитиум").setNameZH("引燃合金").setNameJP("イグニチウム").setBaseColorHigh(0xFF3300).setRawColorHigh(0xFF3300).setRawColorLow(0x7F1900).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(10.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_RED).setBlockLightLevel(10).setIgnitedByLava(true).setBlockLightMode("DYNAMIC")
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(10.00f).setMiningLevel(4).setOreDropItem("raw_ignitium").setOreSmeltingXP(3.0f).setOreLightLevel(5).setOreLightMode("DYNAMIC")
        );
        MATERIALS.put("cursium", new Material()
            .setName("cursium").setNameEN("Cursium").setNameFR("Cursium").setNameES("Cursio").setNameIT("Cursio").setNameDE("Cursium")
            .setNamePT("Cursio").setNameRU("Курсиум").setNameZH("诅咒合金").setNameJP("カージウム").setBaseColorHigh(0x330066).setRawColorHigh(0x330066).setRawColorLow(0x190033).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(10.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(10.00f).setMiningLevel(4).setOreDropItem("raw_cursium").setOreSmeltingXP(3.0f)
        );
        MATERIALS.put("sky_steel", new Material()
            .setName("sky_steel").setNameEN("Sky Steel").setNameFR("Acier Céleste").setNameES("Acero Celeste").setNameIT("Acciaio Celeste").setNameDE("Himmelsstahl")
            .setNamePT("Aço Celeste").setNameRU("Небесная сталь").setNameZH("苍穹钢").setNameJP("スカイスチール").setBaseColorHigh(0x99CCFF).setRawColorHigh(0x99CCFF).setRawColorLow(0x4C667F).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_BLUE).setJumpFactor(1.5f)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_sky_steel").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("sky_bronze", new Material()
            .setName("sky_bronze").setNameEN("Sky Bronze").setNameFR("Bronze Céleste").setNameES("Bronce Celeste").setNameIT("Bronzo Celeste").setNameDE("Himmelsbronze")
            .setNamePT("Bronze Celeste").setNameRU("Небесная бронза").setNameZH("苍穹青铜").setNameJP("スカイブロンズ").setBaseColorHigh(0xCC9966).setRawColorHigh(0xCC9966).setRawColorLow(0x664C33).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_ORANGE).setSpeedFactor(1.5f)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.33f).setMiningLevel(3).setOreDropItem("raw_sky_bronze").setOreSmeltingXP(1.2f)
        );
        MATERIALS.put("sky_osmium", new Material()
            .setName("sky_osmium").setNameEN("Sky Osmium").setNameFR("Osmium Céleste").setNameES("Osmio Celeste").setNameIT("Osmio Celeste").setNameDE("Himmelsosmium")
            .setNamePT("Ósmio Celeste").setNameRU("Небесный осмий").setNameZH("苍穹锇").setNameJP("スカイオスミウム").setBaseColorHigh(0xBED6FF).setRawColorHigh(0xBED6FF).setRawColorLow(0x5F6B7F).setBaseType("ingot")
            .setRarity(Rarity.RARE).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(2.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_BLUE).setJumpFactor(1.5f)
            .setOreHardnessFactor(4.00f).setOreResistanceFactor(2.00f).setMiningLevel(4).setOreDropItem("raw_sky_osmium").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("antimony", new Material()
            .setName("antimony").setNameEN("Antimony").setNameFR("Antimoine").setNameES("Antimonio").setNameIT("Antimonio").setNameDE("Antimon")
            .setNamePT("Antimônio").setNameRU("Сурьма").setNameZH("锑").setNameJP("アンチモン").setBaseColorHigh(0xE0E0E0).setRawColorHigh(0xE0E0E0).setRawColorLow(0x8A8A8A).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.50f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.50f).setMiningLevel(2).setOreDropItem("raw_antimony").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("beryllium", new Material()
            .setName("beryllium").setNameEN("Beryllium").setNameFR("Béryllium").setNameES("Berilio").setNameIT("Berillio").setNameDE("Beryllium")
            .setNamePT("Berílio").setNameRU("Бериллий").setNameZH("铍").setNameJP("ベリリウム").setBaseColorHigh(0xD0E0D0).setRawColorHigh(0xD0E0D0).setRawColorLow(0x6B7A6B).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.67f).setBlockResistanceFactor(0.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_LIGHT_GREEN)
            .setOreHardnessFactor(1.67f).setOreResistanceFactor(0.67f).setMiningLevel(2).setOreDropItem("raw_beryllium").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("battery_alloy", new Material()
            .setName("battery_alloy").setNameEN("Battery Alloy").setNameFR("Alliage pour Batterie").setNameES("Aleación de Batería").setNameIT("Lega per Batteria").setNameDE("Batterie-Legierung")
            .setNamePT("Liga de Bateria").setNameRU("Аккумуляторный сплав").setNameZH("电池合金").setNameJP("バッテリー合金").setBaseColorHigh(0x333333).setRawColorHigh(0x333333).setRawColorLow(0x191919).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("raw_battery_alloy").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("blastproof_alloy", new Material()
            .setName("blastproof_alloy").setNameEN("Blastproof Alloy").setNameFR("Alliage Antidéflagrant").setNameES("Aleación Antiexplosión").setNameIT("Lega Antiesplosione").setNameDE("Explosionsgeschützte Legierung")
            .setNamePT("Liga à Prova de Explosão").setNameRU("Взрывозащищенный сплав").setNameZH("防爆合金").setNameJP("耐爆合金").setBaseColorHigh(0x444444).setRawColorHigh(0x444444).setRawColorLow(0x222222).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(33.33f).setBlockResistanceFactor(333.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(26.67f).setOreResistanceFactor(250.00f).setMiningLevel(4).setOreDropItem("raw_blastproof_alloy").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("cadmium", new Material()
            .setName("cadmium").setNameEN("Cadmium").setNameFR("Cadmium").setNameES("Cadmio").setNameIT("Cadmio").setNameDE("Cadmium")
            .setNamePT("Cádmio").setNameRU("Кадмий").setNameZH("镉").setNameJP("カドミウム").setBaseColorHigh(0x999999).setRawColorHigh(0x999999).setRawColorLow(0x555555).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.50f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.50f).setMiningLevel(2).setOreDropItem("raw_cadmium").setOreSmeltingXP(0.7f)
        );
        MATERIALS.put("chromium", new Material()
            .setName("chromium").setNameEN("Chromium").setNameFR("Chrome").setNameES("Cromo").setNameIT("Cromo").setNameDE("Chrom")
            .setNamePT("Cromo").setNameRU("Хром").setNameZH("铬").setNameJP("クロム").setBaseColorHigh(0xE0E0E0).setRawColorHigh(0xE0E0E0).setRawColorLow(0x7A7A7A).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.67f).setMiningLevel(3).setOreDropItem("raw_chromium").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("cupronickel", new Material()
            .setName("cupronickel").setNameEN("Cupronickel").setNameFR("Cupronickel").setNameES("Cuproníquel").setNameIT("Cupro-nichel").setNameDE("Kupfernickel")
            .setNamePT("Cuproníquel").setNameRU("Мельхиор").setNameZH("白铜").setNameJP("キュプロニッケル").setBaseColorHigh(0xE0D0C0).setRawColorHigh(0xE0D0C0).setRawColorLow(0x706860).setBaseType("ingot")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(1.67f).setBlockResistanceFactor(0.83f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_ORANGE)
            .setOreHardnessFactor(1.67f).setOreResistanceFactor(0.83f).setMiningLevel(2).setOreDropItem("raw_cupronickel").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("kanthal", new Material()
            .setName("kanthal").setNameEN("Kanthal").setNameFR("Kanthal").setNameES("Kanthal").setNameIT("Kanthal").setNameDE("Kanthal")
            .setNamePT("Kanthal").setNameRU("Кантал").setNameZH("康泰尔合金").setNameJP("カンタル").setBaseColorHigh(0x999977).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(1.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BROWN)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(1.33f).setMiningLevel(3).setOreDropItem("raw_kanthal").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("plutonium", new Material()
            .setName("plutonium").setNameEN("Plutonium").setNameFR("Plutonium").setNameES("Plutonio").setNameIT("Plutonio").setNameDE("Plutonium")
            .setNamePT("Plutónio").setNameRU("Плутоний").setNameZH("钚").setNameJP("プルトニウム").setBaseColorHigh(0x33FF00).setRawColorHigh(0x33FF00).setRawColorLow(0x197F00).setBaseType("self")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(16.67f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_GREEN)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(16.67f).setMiningLevel(4).setOreSmeltingXP(5.0f)
        );
        MATERIALS.put("silicon", new Material()
            .setName("silicon").setNameEN("Silicon").setNameFR("Silicium").setNameES("Silicio").setNameIT("Silicio").setNameDE("Silizium")
            .setNamePT("Silício").setNameRU("Кремний").setNameZH("硅").setNameJP("シリコン").setBaseColorHigh(0x333333).setRawColorHigh(0x333333).setRawColorLow(0x191919).setBaseType("ingot")
            .setTrimmable(false)
            .setBlockHardnessFactor(0.67f).setBlockResistanceFactor(0.17f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(0.67f).setOreResistanceFactor(0.17f).setMiningLevel(1).setOreDropItem("raw_silicon")
        );
        MATERIALS.put("titanium", new Material()
            .setName("titanium").setNameEN("Titanium").setNameFR("Titane").setNameES("Titanio").setNameIT("Titanio").setNameDE("Titan")
            .setNamePT("Titânio").setNameRU("Титан").setNameZH("钛").setNameJP("チタン").setBaseColorHigh(0xD0D0D0).setRawColorHigh(0xD0D0D0).setRawColorLow(0x686868).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(10.00f).setBlockResistanceFactor(33.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.METAL)
            .setOreHardnessFactor(8.00f).setOreResistanceFactor(25.00f).setMiningLevel(4).setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("tungsten", new Material()
            .setName("tungsten").setNameEN("Tungsten").setNameFR("Tungstène").setNameES("Tungsteno").setNameIT("Tungsteno").setNameDE("Wolfram")
            .setNamePT("Tungstênio").setNameRU("Вольфрам").setNameZH("钨").setNameJP("タングステン").setBaseColorHigh(0x333333).setRawColorHigh(0x333333).setRawColorLow(0x191919).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(13.33f).setBlockResistanceFactor(83.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(10.00f).setOreResistanceFactor(66.67f).setMiningLevel(4).setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("insanium", new Material()
            .setName("insanium").setNameEN("Insanium").setNameFR("Insanium").setNameES("Insanium").setNameIT("Insanium").setNameDE("Insanium")
            .setNamePT("Insânio").setNameRU("Инсаниум").setNameZH("极简合金").setNameJP("インサニウム").setBaseColorHigh(0x660099).setRawColorHigh(0x660099).setRawColorLow(0x33004C).setBaseType("ingot")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(33.33f).setBlockResistanceFactor(333.33f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(33.33f).setOreResistanceFactor(333.33f).setMiningLevel(4).setOreDropItem("raw_insanium").setOreSmeltingXP(10.0f)
        );
        MATERIALS.put("prosperity", new Material()
            .setName("prosperity").setNameEN("Prosperity").setNameFR("Prospérité").setNameES("Prosperidad").setNameIT("Prosperità").setNameDE("Wohlstand")
            .setNamePT("Prosperidade").setNameRU("Процветание").setNameZH("繁荣").setNameJP("繁栄").setBaseColorHigh(0xE0FFFF).setRawColorHigh(0xE0FFFF).setRawColorLow(0x708080).setBaseType("gem")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.67f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.67f).setMiningLevel(2).setOreDropItem("prosperity_shard")
        );
        MATERIALS.put("inferium", new Material()
            .setName("inferium").setNameEN("Inferium").setNameFR("Inferium").setNameES("Inferium").setNameIT("Inferium").setNameDE("Inferium")
            .setNamePT("Inferium").setNameRU("Инфериум").setNameZH("下等合金").setNameJP("インフェリウム").setBaseColorHigh(0x33FF00).setRawColorHigh(0x33FF00).setRawColorLow(0x198000).setBaseType("gem")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.67f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_GREEN)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.67f).setMiningLevel(1).setOreDropItem("inferium_essence").setOreDropMax(4).setOreDropXPMin(1).setOreDropXPMax(3)
        );
        MATERIALS.put("prudentium", new Material()
            .setName("prudentium").setNameEN("Prudentium").setNameFR("Prudentium").setNameES("Prudentium").setNameIT("Prudentium").setNameDE("Prudentium")
            .setNamePT("Prudentium").setNameRU("Прудентиум").setNameZH("中等合金").setNameJP("プルデンチウム").setBaseColorHigh(0x009900).setRawColorHigh(0x009900).setRawColorLow(0x004D00).setBaseType("gem")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(2.50f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_GREEN)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(2.50f).setMiningLevel(2).setOreDropItem("prudentium").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("tertium", new Material()
            .setName("tertium").setNameEN("Tertium").setNameFR("Tertium").setNameES("Tertium").setNameIT("Tertium").setNameDE("Tertium")
            .setNamePT("Tertium").setNameRU("Терциум").setNameZH("高等合金").setNameJP("ターチウム").setBaseColorHigh(0xFF6600).setRawColorHigh(0xFF6600).setRawColorLow(0x803300).setBaseType("gem")
            .setRarity(Rarity.RARE).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(3.33f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_ORANGE)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(3.33f).setMiningLevel(3).setOreDropItem("tertium").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("imperium", new Material()
            .setName("imperium").setNameEN("Imperium").setNameFR("Imperium").setNameES("Imperium").setNameIT("Imperium").setNameDE("Imperium")
            .setNamePT("Imperium").setNameRU("Империум").setNameZH("超等合金").setNameJP("インペリウム").setBaseColorHigh(0x0099FF).setRawColorHigh(0x0099FF).setRawColorLow(0x004D80).setBaseType("gem")
            .setRarity(Rarity.RARE).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(5.00f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(4.00f).setOreResistanceFactor(5.00f).setMiningLevel(4).setOreDropItem("imperium").setOreSmeltingXP(2.0f)
        );
        MATERIALS.put("supremium", new Material()
            .setName("supremium").setNameEN("Supremium").setNameFR("Supremium").setNameES("Supremium").setNameIT("Supremium").setNameDE("Supremium")
            .setNamePT("Supremium").setNameRU("Супремиум").setNameZH("神等合金").setNameJP("スププレミアム").setBaseColorHigh(0xFF0000).setRawColorHigh(0xFF0000).setRawColorLow(0x800000).setBaseType("gem")
            .setRarity(Rarity.EPIC).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(6.67f).setBlockResistanceFactor(16.67f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_RED)
            .setOreHardnessFactor(6.67f).setOreResistanceFactor(16.67f).setMiningLevel(4).setOreDropItem("supremium").setOreSmeltingXP(5.0f)
        );
        MATERIALS.put("soulium", new Material()
            .setName("soulium").setNameEN("Soulium").setNameFR("Soulium").setNameES("Soulium").setNameIT("Soulium").setNameDE("Soulium")
            .setNamePT("Soulium").setNameRU("Соулиум").setNameZH("灵魂合金").setNameJP("ソウリウム").setBaseColorHigh(0x663300).setRawColorHigh(0x663300).setRawColorLow(0x331A00).setBaseType("ingot")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.67f).setSound(SoundType.SOUL_SAND).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_BROWN)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.67f).setMiningLevel(2).setOreDropItem("soulium").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("ruby", new Material()
            .setName("ruby").setNameEN("Ruby").setNameFR("Rubis").setNameES("Rubí").setNameIT("Rubino").setNameDE("Rubin")
            .setNamePT("Rubi").setNameRU("Рубин").setNameZH("红宝石").setNameJP("ルビー").setBaseColorHigh(0xFF0000).setRawColorHigh(0xFF0000).setRawColorLow(0x8A0000).setBaseType("self")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_RED)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("ruby").setOreDropMax(2).setOreDropXPMin(3).setOreDropXPMax(7)
        );
        MATERIALS.put("sapphire", new Material()
            .setName("sapphire").setNameEN("Sapphire").setNameFR("Saphir").setNameES("Zafiro").setNameIT("Zaffiro").setNameDE("Saphir")
            .setNamePT("Safira").setNameRU("Сапфир").setNameZH("蓝宝石").setNameJP("サファイア").setBaseColorHigh(0x0000FF).setRawColorHigh(0x0000FF).setRawColorLow(0x00008A).setBaseType("self")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_BLUE)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("sapphire").setOreDropMax(2).setOreDropXPMin(3).setOreDropXPMax(7)
        );
        MATERIALS.put("peridot", new Material()
            .setName("peridot").setNameEN("Peridot").setNameFR("Péridot").setNameES("Peridoto").setNameIT("Peridoto").setNameDE("Peridot")
            .setNamePT("Peridoto").setNameRU("Перидот").setNameZH("橄榄石").setNameJP("ペリドット").setBaseColorHigh(0x00FF00).setRawColorHigh(0x00FF00).setRawColorLow(0x008A00).setBaseType("self")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_GREEN)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("peridot").setOreDropMax(2).setOreDropXPMin(3).setOreDropXPMax(7)
        );
        MATERIALS.put("topaz", new Material()
            .setName("topaz").setNameEN("Topaz").setNameFR("Topaze").setNameES("Topacio").setNameIT("Topazio").setNameDE("Topas")
            .setNamePT("Topázio").setNameRU("Топаз").setNameZH("黄玉").setNameJP("トパーズ").setBaseColorHigh(0xFFFF00).setRawColorHigh(0xFFFF00).setRawColorLow(0x8A8A00).setBaseType("self")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(3.33f).setBlockResistanceFactor(1.00f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_YELLOW)
            .setOreHardnessFactor(3.33f).setOreResistanceFactor(1.00f).setMiningLevel(2).setOreDropItem("topaz").setOreDropMax(2).setOreDropXPMin(3).setOreDropXPMax(7)
        );
        MATERIALS.put("fluorite", new Material()
            .setName("fluorite").setNameEN("Fluorite").setNameFR("Fluorine").setNameES("Fluorita").setNameIT("Fluorite").setNameDE("Fluorit")
            .setNamePT("Fluorita").setNameRU("Флюорит").setNameZH("萤石").setNameJP("蛍石").setBaseColorHigh(0xFFCCFF).setRawColorHigh(0xFFCCFF).setRawColorLow(0x995599).setBaseType("self")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.67f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_PINK)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.67f).setMiningLevel(2).setOreDropItem("fluorite").setOreDropMax(4).setOreDropXPMin(1).setOreDropXPMax(5)
        );
        MATERIALS.put("ametrine", new Material()
            .setName("ametrine").setNameEN("Ametrine").setNameFR("Amétrine").setNameES("Ametrina").setNameIT("Ametrina").setNameDE("Ametrin")
            .setNamePT("Ametrina").setNameRU("Аметрин").setNameZH("紫黄晶").setNameJP("アメトリン").setBaseColorHigh(0xCC66FF).setRawColorHigh(0xCC66FF).setRawColorLow(0x7A3D99).setBaseType("self")
            .setRarity(Rarity.RARE).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(6.67f).setSound(SoundType.AMETHYST).setInstrument(NoteBlockInstrument.HARP).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(6.67f).setMiningLevel(3).setOreDropItem("ametrine").setOreDropMax(2).setOreDropXPMin(5).setOreDropXPMax(10)
        );
        MATERIALS.put("cinnabar", new Material()
            .setName("cinnabar").setNameEN("Cinnabar").setNameFR("Cinabre").setNameES("Cinabrio").setNameIT("Cinabro").setNameDE("Zinnober")
            .setNamePT("Cinábrio").setNameRU("Киноварь").setNameZH("朱砂").setNameJP("辰砂").setBaseColorHigh(0xCC0000).setRawColorHigh(0xCC0000).setRawColorLow(0x7A0000).setBaseType("self")
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.50f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_RED)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("cinnabar").setOreDropMax(3).setOreDropXPMin(1).setOreDropXPMax(3)
        );
        MATERIALS.put("niter", new Material()
            .setName("niter").setNameEN("Niter").setNameFR("Nitre").setNameES("Nitro").setNameIT("Nitro").setNameDE("Salpeter")
            .setNamePT("Nitro").setNameRU("Селитра").setNameZH("硝石").setNameJP("硝石").setBaseColorHigh(0xFFFFFF).setBaseType("self")
            .setTrimmable(false)
            .setBlockHardnessFactor(0.33f).setBlockResistanceFactor(0.08f).setSound(SoundType.SAND).setInstrument(NoteBlockInstrument.SNARE).setMapColor(MapColor.SNOW)
            .setOreHardnessFactor(0.33f).setOreResistanceFactor(0.08f).setMiningLevel(0).setOreDropItem("niter").setOreDropMax(4).setOreDropXPMax(2)
        );
        MATERIALS.put("sulfur", new Material()
            .setName("sulfur").setNameEN("Sulfur").setNameFR("Soufre").setNameES("Azufre").setNameIT("Zolfo").setNameDE("Schwefel")
            .setNamePT("Enxofre").setNameRU("Сера").setNameZH("硫").setNameJP("硫黄").setBaseColorHigh(0xFFFF00).setBaseType("self")
            .setFireproof(true).setTrimmable(false)
            .setBlockHardnessFactor(0.33f).setBlockResistanceFactor(0.08f).setSound(SoundType.SAND).setInstrument(NoteBlockInstrument.SNARE).setMapColor(MapColor.COLOR_YELLOW)
            .setOreHardnessFactor(0.33f).setOreResistanceFactor(0.08f).setMiningLevel(0).setOreDropItem("sulfur").setOreDropMax(4).setOreDropXPMin(1).setOreDropXPMax(3)
        );
        MATERIALS.put("apatite", new Material()
            .setName("apatite").setNameEN("Apatite").setNameFR("Apatite").setNameES("Apatita").setNameIT("Apatite").setNameDE("Apatit")
            .setNamePT("Apatita").setNameRU("Апатит").setNameZH("磷灰石").setNameJP("アパタイト").setBaseColorHigh(0x3399FF).setRawColorHigh(0x3399FF).setRawColorLow(0x194C80).setBaseType("self")
            .setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.50f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("apatite").setOreDropMax(6).setOreDropXPMin(1).setOreDropXPMax(4)
        );
        MATERIALS.put("cobalt", new Material()
            .setName("cobalt").setNameEN("Cobalt").setNameFR("Cobalt").setNameES("Cobalto").setNameIT("Cobalto").setNameDE("Kobalt")
            .setNamePT("Cobalto").setNameRU("Кобальт").setNameZH("钴").setNameJP("コバルト").setBaseColorHigh(0x0000FF).setRawColorHigh(0x0000FF).setRawColorLow(0x000080).setBaseType("ingot")
            .setRarity(Rarity.RARE).setFireproof(true).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(4.00f).setBlockResistanceFactor(2.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLUE)
            .setOreHardnessFactor(4.00f).setOreResistanceFactor(2.00f).setMiningLevel(4).setOreDropItem("raw_cobalt").setOreSmeltingXP(1.5f)
        );
        MATERIALS.put("certus_quartz", new Material()
            .setName("certus_quartz").setNameEN("Certus Quartz").setNameFR("Quartz Certus").setNameES("Cuarzo Certus").setNameIT("Quarzo Certus").setNameDE("Certus-Quarz")
            .setNamePT("Quartzo Certus").setNameRU("Истинный кварц").setNameZH("赛特斯石英").setNameJP("サータスクォーツ").setBaseColorHigh(0xCFEFFF).setRawColorHigh(0xCFEFFF).setRawColorLow(0x6AADD4).setBaseType("self")
            .setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.50f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("certus_quartz_crystal").setOreDropMax(2).setOreDropXPMin(2).setOreDropXPMax(5)
        );
        MATERIALS.put("charged_certus_quartz", new Material()
            .setName("charged_certus_quartz").setNameEN("Charged Certus Quartz").setNameFR("Quartz Certus Chargé").setNameES("Cuarzo Certus Cargado").setNameIT("Quarzo Certus Carico").setNameDE("Geladener Certus-Quarz")
            .setNamePT("Quartzo Certus Carregado").setNameRU("Заряженный истинный кварц").setNameZH("充能赛特斯石英").setNameJP("充填サータスクォーツ").setBaseColorHigh(0x80D0FF).setRawColorHigh(0x80D0FF).setRawColorLow(0x3B88C2).setBaseType("self").setBaseItemName("charged_certus_quartz_crystal")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(0.50f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_LIGHT_BLUE)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(0.50f).setMiningLevel(1).setOreDropItem("charged_certus_quartz_crystal").setOreDropXPMin(5).setOreDropXPMax(10).setOreLightLevel(3).setOreLightMode("DYNAMIC")
        );
        MATERIALS.put("fluix", new Material()
            .setName("fluix").setNameEN("Fluix").setNameFR("Fluix").setNameES("Fluix").setNameIT("Fluix").setNameDE("Fluix")
            .setNamePT("Fluix").setNameRU("Флюикс").setNameZH("福鲁伊克斯").setNameJP("フルクリスタル").setBaseColorHigh(0x660099).setRawColorHigh(0x660099).setRawColorLow(0x33004D).setBaseType("self").setBaseItemName("fluix_crystal")
            .setRarity(Rarity.UNCOMMON).setBeacon(true).setTrimmable(true)
            .setBlockHardnessFactor(2.67f).setBlockResistanceFactor(0.67f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_PURPLE)
            .setOreHardnessFactor(2.67f).setOreResistanceFactor(0.67f).setMiningLevel(1).setOreDropItem("fluix_crystal").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("salt", new Material()
            .setName("salt").setNameEN("Salt").setNameFR("Sel").setNameES("Sal").setNameIT("Sale").setNameDE("Salz")
            .setNamePT("Sal").setNameRU("Соль").setNameZH("盐").setNameJP("食塩").setBaseColorHigh(0xFFFFFF).setBaseType("self")
            .setTrimmable(false)
            .setBlockHardnessFactor(0.33f).setBlockResistanceFactor(0.08f).setSound(SoundType.SAND).setInstrument(NoteBlockInstrument.SNARE).setMapColor(MapColor.SNOW)
            .setOreHardnessFactor(0.33f).setOreResistanceFactor(0.08f).setMiningLevel(0).setOreDropItem("salt").setOreDropMax(4).setOreDropXPMax(1)
        );
        MATERIALS.put("coke", new Material()
            .setName("coke").setNameEN("Coke").setNameFR("Coke").setNameES("Coque").setNameIT("Coke").setNameDE("Koks")
            .setNamePT("Coque").setNameRU("Кокс").setNameZH("焦炭").setNameJP("コークス").setBaseColorHigh(0x333333).setBaseType("self")
            .setBeacon(true).setTrimmable(false).setFuelTime(3200)
            .setBlockHardnessFactor(2.00f).setBlockResistanceFactor(1.00f).setSound(SoundType.METAL).setInstrument(NoteBlockInstrument.IRON_XYLOPHONE).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(2.00f).setOreResistanceFactor(1.00f).setMiningLevel(1).setOreDropItem("coke").setOreSmeltingXP(1.0f)
        );
        MATERIALS.put("graphite", new Material()
            .setName("graphite").setNameEN("Graphite").setNameFR("Graphite").setNameES("Grafito").setNameIT("Grafite").setNameDE("Graphit")
            .setNamePT("Grafite").setNameRU("Графит").setNameZH("石墨").setNameJP("黒鉛").setBaseColorHigh(0x303030).setBaseType("self")
            .setBeacon(true).setTrimmable(false)
            .setBlockHardnessFactor(1.33f).setBlockResistanceFactor(0.33f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(1.33f).setOreResistanceFactor(0.33f).setMiningLevel(1).setOreDropItem("graphite").setOreSmeltingXP(0.8f)
        );
        MATERIALS.put("carbon", new Material()
            .setName("carbon").setNameEN("Carbon").setNameFR("Carbone").setNameES("Carbono").setNameIT("Carbonio").setNameDE("Kohlenstoff")
            .setNamePT("Carbono").setNameRU("Углерод").setNameZH("碳").setNameJP("炭素").setBaseColorHigh(0x1F1F1F).setBaseType("self")
            .setBeacon(true).setTrimmable(false)
            .setBlockHardnessFactor(1.67f).setBlockResistanceFactor(0.42f).setSound(SoundType.STONE).setInstrument(NoteBlockInstrument.BASEDRUM).setMapColor(MapColor.COLOR_BLACK)
            .setOreHardnessFactor(1.67f).setOreResistanceFactor(0.42f).setMiningLevel(1).setOreDropItem("carbon").setOreSmeltingXP(0.8f)
        );
    }
    public static Material get(String name) {
        return MATERIALS.get(name);
    }
}